/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './angular2-jwt.module';
import * as import2 from './auth-http.service';
import * as import3 from '@angular/core/src/di/injector';
import * as import4 from './auth-config';
import * as import5 from '@angular/http/src/http';
import * as import6 from '@angular/http/src/base_request_options';
class Angular2JwtModuleInjector extends import0.NgModuleInjector<import1.Angular2JwtModule> {
  _Angular2JwtModule_0:import1.Angular2JwtModule;
  __AuthHttp_1:import2.AuthHttp;
  constructor(parent:import3.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _AuthHttp_1():import2.AuthHttp {
    if ((this.__AuthHttp_1 == null)) { (this.__AuthHttp_1 = new import2.AuthHttp(this.parent.get(import4.AuthConfig),this.parent.get(import5.Http),this.parent.get(import6.RequestOptions))); }
    return this.__AuthHttp_1;
  }
  createInternal():import1.Angular2JwtModule {
    this._Angular2JwtModule_0 = new import1.Angular2JwtModule();
    return this._Angular2JwtModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.Angular2JwtModule)) { return this._Angular2JwtModule_0; }
    if ((token === import2.AuthHttp)) { return this._AuthHttp_1; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const Angular2JwtModuleNgFactory:import0.NgModuleFactory<import1.Angular2JwtModule> = new import0.NgModuleFactory(Angular2JwtModuleInjector,import1.Angular2JwtModule);